" vundle.vim must be sourced first
" All of the plugins are installed with Vundle from this file.
source ~/.vim/vundle.vim

" Plugin-specific configuration.
source ~/.vim/plugin_config.vim

" All of the Vim configuration.
source ~/.vim/config.vim

" All hotkeys, not depedant on plugins, are bound here.
source ~/.vim/bindings.vim
