" Plugins installed with vim-plug
source ~/.vim/plug.vim

" All hotkeys, not depedant on plugins, are bound here.
source ~/.vim/bindings.vim

" Plugin-specific configuration.
source ~/.vim/plugin_config.vim
source ~/.vim/coc_config.vim

" User defined functions.
source ~/.vim/functions.vim

" All of the Vim configuration.
source ~/.vim/config.vim

