#!/bin/bash

# meant to be run with `bash -c "path/to/wlaunch"` when running from e.g. a Windows shortcut

# explicitly needed when launching with bash -c form Windows
# source ~/.bashrc
export DISPLAY=$(ipconfig.exe | awk '/IPv4/ {sub("\r",":0"); print $NF;exit}')

# export DISPLAY=$1;
echo "Using Display $1"
i3
