# Start pyenv to be able to switch python verions
eval "$(pyenv init -)"

# start Thesis Environment
function thesis_start {
    source /home/woowapdabug/projects/thesis/python/bin/activate
    cd /home/woowapdabug/projects/thesis/python/src/
}

# start Node Version Manager (nvm)
function nvm_start {
    source /usr/share/nvm/init-nvm.sh
}

# start Python Environment
function python_start {
    source /home/woowapdabug/projects/python/bin/activate
    cd /home/woowapdabug/projects/python/src/
}

# Deafult editor
export EDITOR="vim"
export VISUAL="vim"

# Android Build configuration for Ionic
export JAVA_HOME="$HOME/programs/java/jdk1.8.0_151"
export ANDROID_SDK_HOME="$HOME/programs/android/sdk"
export ANDROID_STUDIO_HOME="$HOME/programs/android/studio"

export PATH="${PATH}:$ANDROID_SDK_HOME/tools:$ANDROID_SDK_HOME/platform-tools"
export PATH="${PATH}:$ANDROID_STUDIO_HOME/gradle/gradle-4.1/bin"
export PATH="${PATH}:$JAVA_HOME/bin"

# Ecobloom Arduino enviromental variables
export ECOBLOOM_ARDUINO_HOME="$HOME/projects/ecobloom/arduino"
export ESP_ARDUINO_HOME="$HOME/programs/arduino"

# Path to your oh-my-zsh installation.
# https://github.com/robbyrussell/oh-my-zsh.git
export ZSH=$HOME/dotfiles/zsh/oh-my-zsh

ZSH_THEME="xiong-chiamiov-plus"

# Plugins
plugins=(
        git 
        vi-mode
        )

source $ZSH/oh-my-zsh.sh

# Kill the vi mode lag
export KEYTIMEOUT=1

# Update system
function system_update {
    sudo pacman -Syu
    yaourt -Syua
}

# Function to switch and save the current path
function pwd {  
  builtin pwd "$@";
  echo "$PWD" > ~/.cwd;
}
export cd  
alias cwd='cd "$(cat ~/.cwd)"' 

# Keybinds
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search
