stty stop undef
stty start undef

xrdb ~/.Xresources

# Are we on a terminal? Dissable archaich C-S C-Q feature
# Not disabling this can cause issues with nvim if we want to use those keys
# https://stackoverflow.com/questions/14737703/vim-unresponsive-after-a-c-x-c-s-sequence
if [ -t 0 ];
then
    stty sane
    stty stop ''
    stty start ''
    stty werase ''
fi

# Print Git status of projects
function project_gitstatus {
    echo "----------------"
    echo "$1"
    git -C "$1" status
    echo "----------------\n"
}

project_gitstatus "${HOME}/dotfiles"

# Connect to cloud machine
#export gcloud_machine=35.237.99.67

# Allow aliases in sudo
# from: https://askubuntu.com/questions/22037/aliases-not-available-when-using-sudo
alias sudo='sudo -E'

# start Node Version Manager (nvm)
function nvm_start {
    source /usr/share/nvm/init-nvm.sh
}

# start Python Environment
function python_start {
    source /home/blasco/projects/python/bin/activate
    cd /home/blasco/projects/python/src/
}

# Deafult editor
export EDITOR="vim"
export VISUAL="vim"

# ESP Development
alias gdb-esp='$HOME/programs/arduino/esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-gdb'

# Path to your oh-my-zsh installation.
# https://github.com/robbyrussell/oh-my-zsh.git
export ZSH=$HOME/dotfiles/zsh/oh-my-zsh

ZSH_THEME="xiong-chiamiov-plus"

# Plugins
plugins=(
        git 
        vi-mode
        autojump
        docker
        docker-compose
        zsh-better-npm-completion
        )

source $ZSH/oh-my-zsh.sh

# Kill the vi mode lag
export KEYTIMEOUT=1

# Update system
function system_update {
    sudo pacman -S npm --overwrite='*'
    sudo pacman -Syu
    yaourt -Syua --noconfirm
}

# Function to switch and save the current path
function pwd {  
  builtin pwd "$@";
  echo "$PWD" > ~/.cwd;
}
export cd  
alias cwd='cd "$(cat ~/.cwd)"' 

# Keybinds
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

# FZF
if [[ $(uname -n) == "arch" ]]; then
    source /etc/profile.d/fzf.zsh
fi
if [[ $(uname -n) == "ubuntu-desktop" ]]; then
    [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
fi

# ripgrep find files:
alias rgf='rg --files | rg'

# History size
export HISTSIZE=1000000000
export SAVEHIST=$HISTSIZE
setopt EXTENDED_HISTORY

# Gcloud
export PATH="${PATH}:${HOME}/programs/google-cloud-sdk/bin"
# The next line enables shell command completion for gcloud.
if [ -f '/home/blasco/programs/google-cloud-sdk/completion.bash.inc' ]; then . '/home/blasco/programs/google-cloud-sdk/completion.bash.inc'; fi

# Google Chrome
export CHROME_BIN=/usr/bin/google-chrome

# Autojump
[[ -s /etc/profile.d/autojump.sh ]] && source /etc/profile.d/autojump.sh

# Load Node Version Manager (nvm)
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use 

# Android Build configuration for Ionic
export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
export ANDROID_STUDIO_HOME="$HOME/Programs/android-studio-ide-201.7042882-linux/android-studio"
export GRADLE_HOME="$HOME/Programs/gradle-6.5-bin/gradle-6.5"

export PATH="${PATH}:$ANDROID_STUDIO_HOME/platform-tools"
export PATH="${PATH}:$ANDROID_STUDIO_HOME/tools"
export PATH="${PATH}:$GRADLE_HOME/bin"
