# Print Git status of projects
function project_gitstatus {
    echo "----------------"
    echo "$1"
    git -C "$1" status
    echo "----------------\n"
}

project_gitstatus "${HOME}/dotfiles"
project_gitstatus "${HOME}/projects/blog/chip8"
project_gitstatus "${HOME}/projects/blog/ftp_client"
project_gitstatus "${HOME}/projects/freelancer/project_planning"

# Connect to cloud machine
export gcloud_machine=35.237.99.67

# Start pyenv to be able to switch python verions
eval "$(pyenv init -)"

# start Thesis Environment
function gnssr_start {
    source /home/blasco/projects/thesis/py_venv_gnssr/bin/activate
        cd /home/blasco/projects/thesis/py_venv_gnssr/src/
}
function wavpy_start {
    source /home/blasco/projects/thesis/py_venv_wavpy/bin/activate
        cd /home/blasco/projects/thesis/py_venv_wavpy/src/
}

# Allow aliases in sudo
# from: https://askubuntu.com/questions/22037/aliases-not-available-when-using-sudo
alias sudo='sudo '

function ecobloom_start {
    nvm_start
    nvm use lts/carbon
    cd /home/blasco/projects/ecobloom
}

# start Node Version Manager (nvm)
function nvm_start {
    source /usr/share/nvm/init-nvm.sh
}

# start Python Environment
function python_start {
    source /home/blasco/projects/python/bin/activate
    cd /home/blasco/projects/python/src/
}

# Deafult editor
export EDITOR="nvim"
export VISUAL="nvim"

# Android Build configuration for Ionic
export JAVA_HOME="$HOME/programs/java/jdk1.8.0_151"
export ANDROID_HOME="$HOME/programs/android/sdk"
export ANDROID_STUDIO_HOME="$HOME/programs/android/studio"

export PATH="${PATH}:$ANDROID_HOME/tools"
export PATH="${PATH}:$ANDROID_HOME/tools/bin"
export PATH="${PATH}:$ANDROID_HOME/platform-tools"
export PATH="${PATH}:$ANDROID_HOME/emulator"
export PATH="${PATH}:$ANDROID_STUDIO_HOME/gradle/gradle-4.1/bin"
export PATH="${PATH}:$JAVA_HOME/bin"
export PATH="${PATH}:/home/blasco/.gem/ruby/2.6.0/bin"

# Ecobloom Arduino enviromental variables
export ECOBLOOM_ARDUINO_HOME="$HOME/projects/ecobloom/ecogarden/arduino"
export ESP_ARDUINO_HOME="$HOME/programs/arduino"

alias gdb-esp='$HOME/programs/arduino/esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-gdb'

# Path to your oh-my-zsh installation.
# https://github.com/robbyrussell/oh-my-zsh.git
export ZSH=$HOME/dotfiles/zsh/oh-my-zsh

ZSH_THEME="xiong-chiamiov-plus"

# Plugins
plugins=(
        git 
        vi-mode
        )

source $ZSH/oh-my-zsh.sh

# Kill the vi mode lag
export KEYTIMEOUT=1

# Update system
function system_update {
    sudo pacman -Syu
    yaourt -Syua --noconfirm
}

# Function to switch and save the current path
function pwd {  
  builtin pwd "$@";
  echo "$PWD" > ~/.cwd;
}
export cd  
alias cwd='cd "$(cat ~/.cwd)"' 

# Keybinds
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

# FZF
source /etc/profile.d/fzf.zsh
# ripgrep find files:
alias rgf='rg --files | rg'
